steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t gcr.io/totemic-access-464412-c6/webapp:$COMMIT_SHA .
    secretEnv:
      []
     env:
      - 'DOCKER_BUILDKIT=1'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/totemic-access-464412-c6/webapp:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'webapp'
      - '--image'
      - 'gcr.io/totemic-access-464412-c6/webapp:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
images:
  - 'gcr.io/totemic-access-464412-c6/webapp:$COMMIT_SHA'
